// src/features/products/productData.js
// Add `rating`, `deliveryTime`, `restaurant`, and optional `badge` to each product.
// badge shape: { type: 'sale' | 'new' | 'popular', label: string }

const products = [
  {
    id: 1,
    name: 'Smash Burger',
    price: 12.90,
    image: '/images/Hamburguesa2.jpg',
    category: 'burgers',
    rating: 4.8,
    deliveryTime: '18',
    restaurant: 'Burger Republic',
    badge: { type: 'sale', label: '20% OFF' },
  },
  {
    id: 2,
    name: 'Asado',
    price: 16.50,
    image: '/images/Asado.jpg',
    category: 'pizza',
    rating: 4.7,
    deliveryTime: '22',
    restaurant: 'Pizza Palace',
  },
  {
    id: 3,
    name: 'Rainbow Roll',
    price: 19.00,
    image: '/images/rainbow.jpg',
    category: 'sushi',
    rating: 4.9,
    deliveryTime: '30',
    restaurant: 'Sakura Sushi',
    badge: { type: 'new', label: 'NEW' },
  },
  {
    id: 4,
    name: 'Vegan Bowl',
    price: 11.00,
    image: '/images/vegan.jpg',
    category: 'vegan',
    rating: 4.6,
    deliveryTime: '15',
    restaurant: 'Green Garden',
  },
  {
    id: 5,
    name: 'Truffle Pasta',
    price: 18.00,
    image: '/images/Pasta.jpg',
    category: 'pasta',
    rating: 4.8,
    deliveryTime: '20',
    restaurant: 'La Trattoria',
    badge: { type: 'popular', label: 'POPULAR' },
  },
  {
    id: 6,
    name: 'Crispy Tacos',
    price: 13.50,
    image: '/images/Tacos.jpg',
    category: 'tacos',
    rating: 4.5,
    deliveryTime: '17',
    restaurant: 'Taco Libre',
  },
  {
    id: 7,
    name: 'Asado',
    price: 22.00,
    image: '/images/Asado.jpg',
    category: 'mains',
    rating: 4.9,
    deliveryTime: '35',
    restaurant: 'Smoke & Fire',
  },
  {
    id: 8,
    name: 'Acai Smoothie Bowl',
    price: 9.50,
    image: '/images/Acai.jpg',
    category: 'vegan',
    rating: 4.7,
    deliveryTime: '12',
    restaurant: 'Bloom Kitchen',
    badge: { type: 'new', label: 'NEW' },
  },
];

export default products;